language: node_js
node_js:
- '8'
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn compile
- yarn test
before_deploy:
- npm version from-git
- cp README.md package.json dist/
- cd dist
deploy:
  provider: npm
  email: m.helmich@mittwald.de
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: bcLnZTzuah7QaKQSv98ZNXvwRDQJeemfA8YkXvjxk0lMdr4Qudjn+vmfSVRmq56XcQxvhX9BFhTcZKi4+N5ThbT+hE5GOPjDYx3MetRMkIcvHdsfuzkYxfUvgqdR3uqADHGhutmZntF3Tm85STfWDMPeyHZ4qBANu8QMOy9wb1wp7nZE3UUcX8USzoWuCn6/uzgwTnrFqKdpVRkgY9opVHkJrwTVe3HjGO+b0bPovPFw3TwpuxPDRC1gytS2CUqXWbPMe/SSxVFYqXVgVsXe8LVRZGqfwCZSYx6zLdG21BulBFdyKps6Btm+77jbymNQZZjylR8oT7tt0H6RgwwCH+mqLuzicjSh7vzCfT5AVqBC4LIpyoQ+U9aOqUjo9KI9K5Mzngot9JZ7vafAgMgswBiFs+1/eaZXYL7dPCrHL4yVvcTOcjcIWqiwlVCKxGKlcF4dAyySaHwmy12EikngbswCuJwvh1ofSVI0XjAOROobFklbO4m8fyds5EBBlp2OWcQ/1PkXs0eDAXgo6rF/FxkJ/e2bN5G5SlbTcEtDLXDmYXLs3bHVnOcvnMtly+3sYcjN0bUfp7YT/+nxhSeedOIFqowNnZj/nM68P8pI1NTxNadM4lKrTRb6YG1znh56KXHYPzl5R6R/kYNVL1iO3lWVEpPwrRZ+U84QI2nwaj8=
