language: node_js
node_js:
- '8'
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn compile
- yarn test
before_deploy:
- npm version from-git
- cp README.md package.json dist/
- cd dist
deploy:
  provider: npm
  edge: true
  email: m.helmich@mittwald.de
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: tbvWdzsrnfdfwuDKm9TM7DajRbdrS/KE6XaRZ5N2KQNpP6dE3pzPglrF4DjEJN7tO9dhEwvl9N/1K0eF6VlCLS/s8z8pEd79IkvJUNTx4/JwG5Ge/R43CIcr19JEGNc6AgcROSh/i4mqgvl1kWIgPLGTCujmeRvtXaOElEV7VxUBaxvOTrRWnMk+ctwezaIGk1wrG8XUTe//kPWDuA59PNp2JjHdkxR2gzereo/B9av9CYtOmF8WIhkkL0OkdD7+7fAkWaq1SUAsGOTSNsB7tym7LzLqrmlIW52Kd9JYaaPmh6C+a4hmsnaSCFMjwnXyxe6qd2Sl8Zp75CF4uvVXD9v05F93M00L9IhvP2UZQwITSSNEfSHbG7+SGmQy9toR7xkzQDxaxNicdd2/KlWKZkzljWf8o0QQYScOCH7MlZU4mYgTSx211TF+EHBgSW6OqXUz3SqneohukVWEqX0s6YF5BttN0Ew6LzwNsxv0/NLqb9R79SYwcAN+F/PqmfNe5ydrcxpG4NSaElTWsHNgdo2IazZAjtKiQG2JIHEU8acdi3YCYUK/PUC2mMnlU1JKFA7hCgSHsckAw1mhdGPhvjiLV8347e3KL3C3RcYKAqzg6AoOBhMKLjxeHR1D7oDzxE/DH3VOFWotZhCCFVXoarkajoRGPpc/ArT10DzVTTQ=
