language: node_js
node_js:
- '8'
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn compile
- yarn test
before_deploy:
- npm version from-git
- cp README.md package.json dist/
- cd dist
deploy:
  provider: npm
  email: m.helmich@mittwald.de
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: atQIajpHMQ6ZrGU4KjvzgRhNokGZfUgNkRkyKy8r02Tn4MTAArC6axTFMAKpW2fccSWSgZ9JCS/HJ55vLXWjBnWeXmjO6OOr9Hnb1/XA6mM6j8exo31TiEWKgRefjEd+NnttjL7QTD7S+iRhZop+xkxVDrzI/nSzhDv+3/Awe1QBngqYR7ZqFrjRp2lK2GAqW29NIm9ugEsGDhCtJE6iwgghph3sL44Kg4zVCMv1yl0A/lIfl5By7KvnsDQtiSf9LVMa+MMcw9mljIp3JqiXa5uD6Ipsa04Uw8WPL2i5z7PcXeoU9xh2dGcoNFNveyhYwXaUf7ZUYbG/VZmE7JvAPfWlt1Goz5qclDHToaF4ueR/vLT5X+UK992tZc8WOL61P8rIUlYSj/+6IPS1dW0F722ogH64QFQW1SzfqKsmDwbQ/3VtVtY1BlPdR6cvTW8nYXANBbkuJ9CIXJELWyqBGipGYOEzDOm7pO0c2fKU5lfD9uZ5OAm5do+QC4bs6x6+2S3c7c5sf2GIcsVxWllMSD8fg3Z0T8Btes8D6HHK3TwSnx+VadQj1basyCuUV9umYFntQrVESAVYZE3sE+f7uMdxZRtHk9uqi6RNBLBCP9DYj+7Ba0O91lTm/g3twzI0jVe+1zynFMibwxpRtmbEitovMzk6cg+YARC8ip8+MzE=
