language: node_js
node_js:
- '12'
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn compile
- yarn test
before_deploy:
- npm version from-git
- cp README.md package.json dist/
- cd dist
deploy:
  provider: npm
  edge: true
  email: m.helmich@mittwald.de
  skip_cleanup: true
  on:
    tags: true
